name: "TestApp.io App Distribution"
description: "GitHub Action that uploads artifacts to TestApp.io App Distribution"
author: "Support <support@testapp.io>"
inputs:
  api_token:
    description: "API Token can be claimed from https://portal.testapp.io/settings/api-credentials"
    required: true
  app_id:
    description: "App ID can be found from your app page in https://portal.testapp.io/apps"
    required: true
  file:
    description: "Artifact to upload (.apk or .ipa)"
    required: true
  notify:
    description: "Send notificaitons to team members about this release"
    required: false
branding:
  color: "blue"
  icon: "send"
runs:
  using: "composite"
  steps:
    - run: curl -Ls https://github.com/testappio/cli/releases/latest/download/install | bash
      shell: bash
    - run: chmod +x ${{ github.action_path }}/entrypoint.sh
      shell: bash
    - run: sh ${{ github.action_path }}/entrypoint.sh
      env:
        INPUT_API_TOKEN: ${{ inputs.api_token }}
        INPUT_APP_ID: ${{ inputs.app_id }}
        INPUT_FILE: ${{ inputs.file }}
        INPUT_NOTIFY: ${{ inputs.notify }}
      shell: bash
