name: "TestApp.io App Distribution"
description: "GitHub Action that uploads artifacts to TestApp.io App Distribution"
author: "Support <support@testapp.io>"
inputs:
  api_token:
    description: "API Token can be claimed from https://portal.testapp.io/settings/api-credentials"
    required: true
  app_id:
    description: "App ID can be found from your app page in https://portal.testapp.io/apps"
    required: true
  file:
    description: "Artifact to upload (.apk or .ipa)"
    required: true
  release_notes:
    description: "Release notes will be visible for testers"
    required: false
  git_release_notes:
    description: "Collect the release notes from the last git commit message"
    required: false
  include_git_commit_id:
    description: "Include the last git commit ID with the release notes"
    required: false
  notify:
    description: "Send notificaitons to team members about this release"
    required: false
branding:
  color: "blue"
  icon: "send"
runs:
  using: "composite"
  steps:
    - run: curl -Ls https://github.com/testappio/cli/releases/download/v1.0.3/install | bash
      shell: bash
    - run: chmod +x ${{ github.action_path }}/entrypoint.sh
      shell: bash
    - run: sh ${{ github.action_path }}/entrypoint.sh
      env:
        INPUT_API_TOKEN: ${{ inputs.api_token }}
        INPUT_APP_ID: ${{ inputs.app_id }}
        INPUT_FILE: ${{ inputs.file }}
        INPUT_RELEASE_NOTES: ${{ inputs.release_notes }}
        INPUT_GIT_RELEASE_NOTES: ${{ inputs.git_release_notes }}
        INPUT_INCLUDE_GIT_COMMIT_ID: ${{ inputs.include_git_commit_id }}
        INPUT_NOTIFY: ${{ inputs.notify }}
      shell: bash
