name: Workflow to upload apk and ipa to TestApp.io app distribution
on: [push, pull_request, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get sample .apk for test purposes
        run: wget https://github.com/testappio/cli/raw/main/sample-apps/sample-app.apk
      - name: Get sample .ipa for test purposes
        run: wget https://github.com/testappio/cli/raw/main/sample-apps/sample-app.ipa
      - name: Upload .apk artifact to TestApp.io app distribution
        uses: ./
        with:
          api_token: ${{secrets.TESTAPPIO_API_TOKEN}}
          app_id: ${{secrets.TESTAPPIO_APP_ID}}
          file: sample-app.apk
          notify: "no"
          debug: true
      - name: Upload .ipa artifact to TestApp.io app distribution
        uses: ./
        with:
          api_token: ${{secrets.TESTAPPIO_API_TOKEN}}
          app_id: ${{secrets.TESTAPPIO_APP_ID}}
          file: sample-app.ipa
          notify: "no"
          debug: true
